name: Android CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # Trigger on version tags (e.g., v1.0.0)

# Environment variables available to all jobs and steps in this workflow
#env:
  # These secrets need to be set in your GitHub repository settings
  # under Settings > Secrets and variables > Actions
#  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
#  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#  MAVEN_CENTRAL_STAGING_PROFILE_ID: ${{ secrets.MAVEN_CENTRAL_STAGING_PROFILE_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test Debug
        run: ./gradlew toast:testDebug
      - name: Test Release
        run: ./gradlew toast:testRelease

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew toast:build

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adoptium'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            ## What's Changed
            - Update library version to ${{ github.ref }}
            - Auto-generated release
          draft: false
          prerelease: false
#      - name: Publish to Maven Central
#        run: |
#          echo "Publishing version: ${GITHUB_REF#refs/tags/v}"
#          ./gradlew publishToMavenCentral --no-parallel --no-daemon
#        env:
#          # These environment variables are used by the maven-publish plugin
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
#          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          MAVEN_CENTRAL_STAGING_PROFILE_ID: ${{ secrets.MAVEN_CENTRAL_STAGING_PROFILE_ID }}
